name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          cache: true

      - name: Clean
        run: |
          flutter clean
          rm -rf build/web

      - name: Create firebase_options.dart file
        run: echo "${{ secrets.FIREBASE_OPTIONS_CONTENT }}" > lib/firebase_options.dart

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Build project (lean HTML renderer + no PWA precache)
        run: |
          FLUTTER_WEB_RENDERER=html \
          flutter build web \
            --release \
            --pwa-strategy=none \
            --tree-shake-icons

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project moneyhooks-1dd85
